package tqk114514.terracuda.mixin;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.StructureManager;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.Beardifier;
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator;
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings;
import net.minecraft.world.level.levelgen.NoiseSettings;
import net.minecraft.world.level.levelgen.RandomState;
import net.minecraft.world.level.levelgen.blending.Blender;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import tqk114514.terracuda.TerraCUDA;
import tqk114514.terracuda.chunk.EmittedChunk;
import tqk114514.terracuda.config.TerracudaConfig;
import tqk114514.terracuda.worldgen.GpuWorldgenService;

/**
 * Hooks {@code NoiseBasedChunkGenerator.fillFromNoise}, the entry point to the NOISE stage.
 *
 * <p>Two modes, both driven from here. In shadow mode the device path runs and the result is thrown
 * away, which is how the chain is checked against a live world without risking one. In takeover mode
 * the chunk is handed to {@link GpuWorldgenService#fill} and vanilla's NOISE stage is cancelled.
 *
 * <p><b>Why the future is returned uncompleted.</b> The device work is serialised on one thread, so
 * blocking the caller here would stall a chunk-task dispatcher thread for the whole time a chunk takes
 * — and those threads are also driving biomes, surface and lighting. Handing back a future lets the
 * dispatcher schedule ahead, and it is the hook batching needs: a batch can only form if the requests
 * pile up somewhere.
 *
 * <p><b>Why the fallback re-enters.</b> Once a future is handed back there is no way to un-cancel, so a
 * device failure cannot be reported by simply returning. Instead the fallback calls
 * {@code fillFromNoise} again, on the completing thread, with a thread-local guard that stops this
 * injection from firing a second time. Nothing has been written to the chunk by then — the service
 * only writes once the whole job has succeeded — so vanilla's own fill is a clean overwrite.
 *
 * <p>Failure containment: everything is inside a try/catch, the switch is off by default, the
 * injection is marked non-required and the mixin config is marked non-required, so a future Minecraft
 * changing the signature degrades to a warning rather than a crash.
 */
@Mixin(NoiseBasedChunkGenerator.class)
public abstract class NoiseBasedChunkGeneratorMixin {

    private static final AtomicLong CHUNKS = new AtomicLong();
    private static final AtomicBoolean REPORTED_FAILURE = new AtomicBoolean();
    private static final AtomicBoolean REPORTED_HEIGHT_MISMATCH = new AtomicBoolean();
    private static final AtomicLong DEFERRED_TO_BEARDIFIER = new AtomicLong();

    /** Set while the fallback is running, so this injection does not fire on it again. */
    private static final ThreadLocal<Boolean> IN_VANILLA = new ThreadLocal<>();

    @Inject(method = "fillFromNoise", at = @At("HEAD"), cancellable = true, require = 0)
    private void terracuda$fillFromNoise(Blender blender, RandomState randomState,
            StructureManager structureManager, ChunkAccess centerChunk,
            CallbackInfoReturnable<CompletableFuture<ChunkAccess>> cir) {
        if (!TerracudaConfig.gpuEnabled() || Boolean.TRUE.equals(IN_VANILLA.get())) {
            return;
        }
        try {
            NoiseBasedChunkGenerator self = (NoiseBasedChunkGenerator) (Object) this;
            NoiseGeneratorSettings settings = self.generatorSettings().value();

            // The design doc routes a non-empty blender to vanilla: it is the legacy-world transition,
            // and blend_alpha/blend_offset/blend_density are not on the device.
            if (!blender.isEmpty()) {
                return;
            }

            // Vanilla's fullNoiseDensity is final_density plus the beardifier, which carves terrain
            // down around structures — so a village's footprint is flattened into the ground rather
            // than sitting on top of it. The device path evaluates the bare density, so a chunk any
            // structure reaches is generated by vanilla rather than generated wrongly. The correct
            // fix is to add the beard value on the host side, and this is what makes that unnecessary
            // to do today: without it the terrain near every structure would quietly differ.
            if (Beardifier.forStructuresInChunk(structureManager, centerChunk.getPos())
                    != Beardifier.EMPTY) {
                // Counted rather than reported once, because a run that logs nothing is ambiguous:
                // it could mean the gate is broken or that no structure was ever in range, and those
                // are very different problems.
                long deferred = DEFERRED_TO_BEARDIFIER.incrementAndGet();
                if (TerracudaConfig.verbose() || deferred % 256 == 1) {
                    TerraCUDA.LOGGER.info("TerraCUDA: chunk {} is reached by a structure's "
                            + "beardifier, so vanilla generates it ({} such chunks seen)",
                            centerChunk.getPos(), deferred);
                }
                return;
            }

            // Vanilla clamps the noise settings to the chunk's own height accessor, and the service is
            // built once per world from the unclamped ones. They agree for a normal dimension; when
            // they do not, this chunk is not the shape the service was sized for.
            NoiseSettings clamped = settings.noiseSettings()
                    .clampToHeightAccessor(centerChunk.getHeightAccessorForGeneration());
            if (!clamped.equals(settings.noiseSettings())) {
                if (REPORTED_HEIGHT_MISMATCH.compareAndSet(false, true)) {
                    TerraCUDA.LOGGER.info("TerraCUDA: this dimension's chunks are {} high from y {}, "
                                    + "but the generator is configured for {} from y {}; those chunks "
                                    + "will be generated by vanilla",
                            clamped.height(), clamped.minY(), settings.noiseSettings().height(),
                            settings.noiseSettings().minY());
                }
                return;
            }

            GpuWorldgenService service = GpuWorldgenService.forWorld(randomState, settings);
            if (!service.isReady()) {
                if (REPORTED_FAILURE.compareAndSet(false, true)) {
                    TerraCUDA.LOGGER.info("TerraCUDA: device unavailable, using vanilla: {}",
                            service.unavailableReason());
                }
                return;
            }

            ChunkPos pos = centerChunk.getPos();
            long start = System.nanoTime();

            if (TerracudaConfig.takeover()) {
                CompletableFuture<ChunkAccess> result = service.fill(centerChunk)
                        .handle((ignored, error) -> error)
                        .thenCompose(error -> {
                            long micros = (System.nanoTime() - start) / 1000;
                            if (error == null) {
                                logChunk(pos, micros, true);
                                return CompletableFuture.completedFuture(centerChunk);
                            }
                            if (REPORTED_FAILURE.compareAndSet(false, true)) {
                                TerraCUDA.LOGGER.warn("TerraCUDA: the device path failed on chunk "
                                        + pos + "; falling back to vanilla for it and continuing",
                                        error);
                            }
                            return vanillaFill(self, blender, randomState, structureManager,
                                    centerChunk);
                        });
                cir.setReturnValue(result);
                return;
            }

            Optional<EmittedChunk> emitted = service.blockIds(pos.x(), pos.z());
            if (emitted.isPresent()) {
                logChunk(pos, (System.nanoTime() - start) / 1000, false);
            }
        } catch (Throwable t) {
            // Never break world generation. Falling through means vanilla writes the chunk, which is
            // correct even if this path had already written part of it.
            if (REPORTED_FAILURE.compareAndSet(false, true)) {
                TerraCUDA.LOGGER.warn("TerraCUDA: the device path failed and is now off", t);
            }
        }
    }

    /** Runs vanilla's own NOISE stage, with this injection suppressed for the duration. */
    private static CompletableFuture<ChunkAccess> vanillaFill(NoiseBasedChunkGenerator self,
            Blender blender, RandomState randomState, StructureManager structureManager,
            ChunkAccess chunk) {
        IN_VANILLA.set(Boolean.TRUE);
        try {
            return self.fillFromNoise(blender, randomState, structureManager, chunk);
        } finally {
            IN_VANILLA.remove();
        }
    }

    private static void logChunk(ChunkPos pos, long micros, boolean takeover) {
        long count = CHUNKS.incrementAndGet();
        if (TerracudaConfig.verbose() || count % 256 == 1) {
            TerraCUDA.LOGGER.info("TerraCUDA{}: chunk {} in {} us ({} chunks seen)",
                    takeover ? "" : " shadow", pos, micros, count);
        }
        if (takeover && TerracudaConfig.timing()) {
            sampleLatency(micros);
        }
    }

    /**
     * The takeover latencies held before a window is reported.
     *
     * <p>A window rather than a running sum because the question M4 left open was the tail, and an
     * average cannot answer it: "every chunk takes 105 ms" and "most take 20 and a few take 800" are
     * the same mean and very different queues.
     */
    private static final int LATENCY_WINDOW = 256;
    private static final long[] LATENCY_SAMPLES = new long[LATENCY_WINDOW];
    private static long latencyFilled;

    /**
     * Records one takeover completion's latency and reports percentiles when a window closes.
     *
     * <p>Only the takeover path samples: its latency was declared the price of the mod, while the
     * shadow path's number is a service profile already covered by {@code ChunkPassProfileTest}.
     * Takeover completions are serialised on the single rules worker — the pipeline hands each
     * chunk across and completes it there, one at a time — so plain fields are safe.
     */
    private static void sampleLatency(long micros) {
        long[] samples = LATENCY_SAMPLES;
        samples[(int) (latencyFilled % LATENCY_WINDOW)] = micros;
        if (++latencyFilled % LATENCY_WINDOW == 0) {
            long[] window = samples.clone();
            java.util.Arrays.sort(window);
            TerraCUDA.LOGGER.info("TerraCUDA: noise-stage latency over the last {} chunks: "
                            + "p50 {} us, p95 {} us, p99 {} us, max {} us",
                    LATENCY_WINDOW,
                    percentile(window, 50), percentile(window, 95), percentile(window, 99),
                    window[window.length - 1]);
        }
    }

    /** Nearest-rank percentile of a sorted array: the ceil(p · count)-th smallest sample. */
    private static long percentile(long[] sorted, int hundredths) {
        int rank = Math.min(sorted.length, (sorted.length * hundredths + 99) / 100);
        return sorted[rank - 1];
    }
}
